theme = "hugo-theme-learn"
DefaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
copyright = "Everything is mine"
languageCode = "fr-fr"
title = "Youtube Map"
googleAnalytics = ""

[languages]
  [languages.fr]
      languageName = "Français"
      weight = 1
  [languages.en]
    languageName = "English"
    weight = 2

# Change the default theme to be use when building the site with Hugo
[params]
themeVariant = "red"
showVisitedLinks = true
disableBreadcrumb = false
disableShortcutsTitle = true
disableNextPrev = false
disableToc = true

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
name = "<i class='fas fa-list'></i> Liste des chaînes"
identifier = "channellist"
url = "/fr/about/"
weight = 21

